- name: install python
  hosts:
    # - single_server
    - vagrant
  become: yes
  gather_facts: no

  tasks:
    - name: install python-minimal
      raw: apt-get install -y python-minimal

- name: single-server ChirpStack setup
  hosts:
#    - single_server
    - vagrant
  roles:
    - base
    - iptables
    - nginx
    - letsencrypt
    - postgresql
    - redis
    - mosquitto
    - mosquitto-auth
    - chirpstack-gateway-bridge
    - chirpstack-network-server
    - chirpstack-application-server
    - chirpstack-geolocation-server
  become: yes
