- name: install
  hosts: 
    - chirpstack_machines
    # - vagrant
  become: yes
  gather_facts: no

  # this is necessary since the mosquitto version 
  # shipped with some distribution has startup issues
  tasks:
    - name: add mosquitto repository
      apt_repository:
        repo: ppa:mosquitto-dev/mosquitto-ppa
        state: present

    - name: install basic packages
      apt: 
        name:
          - python-minimal 
          - python3-pip
          - python-virtualenv
          - rabbitmq-server
        state: present
        update-cache: yes
        cache_valid_time: 7200
      become: yes

    - name: copy python code
      copy:
        src: ../services
        dest: /home/devuser/workspace/
        owner: devuser
        group: devuser

    - name: create virtualenv
      pip:
        requirements: /home/devuser/workspace/services/requirements.txt
        virtualenv: /home/devuser/workspace/env

- name: single-server ChirpStack setup
  hosts: 
    - chirpstack_machines
    # - vagrant
  vars_files:
    - ./variables/config.yml
    - ./twelve/chirpstack.codefornature.org.yml
  roles:
    - base
    - iptables
    - nginx
    - letsencrypt
    - postgresql
    - redis
    - mosquitto
    - mosquitto-auth
    - chirpstack-gateway-bridge
    - chirpstack-network-server
    - chirpstack-application-server
    - chirpstack-geolocation-server
    # install backup programs
    - oefenweb.supervisor
  become: yes

- name: falk extras
  hosts:
    - chirpstack_machines
  tasks:
    - name: create db role for backup scripts
      postgresql_user:
        name: devuser
        password: devuser
        role_attr_flags: SUPERUSER,LOGIN
      become_user: postgres
      become: yes
      no_log: yes
