- name: install
  hosts: 
    - chirpstack_machines
    # - vagrant
  vars_files:
    - ./twelve/chirpstack.codefornature.org.yml
  become: yes
  gather_facts: no

  # this is necessary since the mosquitto version 
  # shipped with some distribution has startup issues
  tasks:
    - name: add key
      apt_key:
        url: "http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key"
        state: present

   # - name: add mosquitto repository
   #   apt_repository:
   #     repo: ppa:mosquitto-dev/mosquitto-ppa
   #     mode: 666
   #     state: present

    - name: install basic packages
      apt: 
        name:
          - python-minimal 
          - python3-pip
          - python-virtualenv
          - rabbitmq-server
        state: present
        update-cache: yes
        cache_valid_time: 7200
      become: yes

    - name: create workspace directory
      file:
        path: "/home/{{ system_user }}/user/workspace"
        state: directory
        mode: '755'
        owner: "{{ system_user }}"
        group: "{{ system_user }}"

    # we might need to set workspace to the correct owner
    # TODO: rather clumsy and should be straighten out
    - name: copy services code
      copy:
        src: "../services"
        dest: "/home/{{ system_user }}/workspace/"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"

    - name: copy clients code
      copy:
        src: "../clients"
        dest: "/home/{{ system_user }}/workspace/"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"

    - name: copy requirements
      copy:
        src: "../requirements.txt"
        dest: "/home/{{ system_user }}/workspace/"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: '644'

    - name: create virtual env
      pip:
        requirements: "/home/{{ system_user }}/workspace/requirements.txt"
        virtualenv: "/home/{{ system_user }}/workspace/env"
      become: true
      become_user: "{{ system_user }}"


- name: single-server ChirpStack setup
  hosts: 
    - chirpstack_machines
    # - vagrant
  vars_files:
    - ./variables/config.yml
    - ./twelve/chirpstack.codefornature.org.yml
  roles:
    - base
    - iptables
    - nginx
    - letsencrypt
    - postgresql
    - redis
    - mosquitto
    - mosquitto-auth
    - chirpstack-gateway-bridge
    - chirpstack-network-server
    - chirpstack-application-server
    - chirpstack-geolocation-server
    # install backup programs
    - oefenweb.supervisor
  become: yes

- name: falk extras
  hosts:
    - chirpstack_machines
  tasks:
    - name: create db role for backup scripts
      postgresql_user:
        name: "{{ system_user }}"
        password: "{{ system_user }}"
        role_attr_flags: SUPERUSER,LOGIN
      become_user: postgres
      become: yes
      no_log: yes
